apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: clo835-app
data:
  # Application Configuration
  APP_COLOR: "blue"
  STUDENT_NAME: "CLO835 Student"
  BACKGROUND_IMAGE_URL: "https://picsum.photos/1920/1080"
  
  # Database Configuration
  DATABASE: "employees"
  DBPORT: "3306"
  
  # S3 Configuration (optional - can be overridden by secrets)
  S3_BUCKET: "your-s3-bucket-name"
  S3_IMAGE_KEY: "backgrounds/sample-background.jpg" 