apiVersion: v1
kind: ServiceAccount
metadata:
  name: clo835
  namespace: final
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::746851085552:role/LabRole
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: CLO835
  namespace: final
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clo835-binding
  namespace: final
subjects:
- kind: ServiceAccount
  name: clo835
  namespace: final
roleRef:
  kind: Role
  name: CLO835
  apiGroup: rbac.authorization.k8s.io 